format = """$directory$git_branch$python$nodejs$rust$golang$docker_context$all\n$character"""

[directory]
format = "[$path]($style) "
style = "bold purple"
truncate_to_repo = false
truncation_length = 3

[character]
error_symbol = "[â¯](bold red)"
success_symbol = "[â¯](bold green)"

[cmd_duration]
disabled = true

[line_break]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true

[package]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold red"

[git_status]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
symbol = "ğŸ "

[nodejs]
format = "[$symbol($version )]($style)"
style = "bold green"
symbol = "â¬¢ "

[rust]
format = "[$symbol($version )]($style)"
style = "bold red"
symbol = "ğŸ¦€ "

[golang]
format = "[$symbol($version )]($style)"
style = "bold cyan"
symbol = "ğŸ¹ "

[docker_context]
format = "[$symbol$context]($style) "
style = "blue bold"
symbol = "ğŸ³ "
